---
output:
  html_document: default
  pdf_document: default
---
```{r warning=F}

############### 0 - safe choice A, 1 - risky choice B #####################
library(rstan); rstan_options(javascript=FALSE)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = T)


# Get list of files in 'data_2' folder with the pattern "riskytimed"
files <- dir(path = "data_2", pattern="riskytimed")

# Read all csv files in the list
data_list <- lapply(paste0("data_2/", files), read.table, header = TRUE, skip = 0, fill = TRUE, sep= ";")

# Concatenate rows of all items in the list into a data frame
dat <- do.call("rbind", data_list)
```





```{r}
# transform to +/- 1; safe - 1, risky +1
dat$cho <- ifelse(dat$choice==0,-1,ifelse(dat$choice==1,1,NA))

ids <- unique(dat$id)
for(j in 1:length(ids)){
  dat$tid[dat$id==ids[j]] <- j
}
tids <- unique(dat$tid)
# only control data
control_dat <- dat[dat$cond=="control",]
# remove fast RTs
rcontrol_dat <- control_dat[control_dat$rt>1,]
# only condition no time pressure
library(dplyr)

rcontrol_dat <- rcontrol_dat %>%
  rowwise() %>%
  mutate(
    oa_condition = sum(c_across(starts_with("oa")) == 0), 
    ob_condition = sum(c_across(starts_with("ob")) == 0)
  ) %>%
  filter(
    (oa_condition == 2 & ob_condition == 0) | 
    (oa_condition == 0 & ob_condition == 2)
  )


library(dplyr)
library(stringr)


df <- rcontrol_dat %>%
  # Swap values if oa_condition is not 0
  rowwise() %>%
  mutate(
    temp_oa1 = if_else(oa_condition != 0, ob1, oa1),
    temp_oa2 = if_else(oa_condition != 0, ob2, oa2),
    temp_oa3 = if_else(oa_condition != 0, ob3, oa3),
    temp_oa4 = if_else(oa_condition != 0, ob4, oa4),
    temp_pa1 = if_else(oa_condition != 0, pb1, pa1),
    temp_pa2 = if_else(oa_condition != 0, pb2, pa2),
    temp_pa3 = if_else(oa_condition != 0, pb3, pa3),
    temp_pa4 = if_else(oa_condition != 0, pb4, pa4),
    temp_ob1 = if_else(oa_condition != 0, oa1, ob1),
    temp_ob2 = if_else(oa_condition != 0, oa2, ob2),
    temp_ob3 = if_else(oa_condition != 0, oa3, ob3),
    temp_ob4 = if_else(oa_condition != 0, oa4, ob4),
    temp_pb1 = if_else(oa_condition != 0, pa1, pb1),
    temp_pb2 = if_else(oa_condition != 0, pa2, pb2),
    temp_pb3 = if_else(oa_condition != 0, pa3, pb3),
    temp_pb4 = if_else(oa_condition != 0, pa4, pb4)
  ) %>%
  ungroup() %>%
  # Rename columns
  #select(-starts_with("oa"), -starts_with("ob"), -starts_with("pa"), -starts_with("pb")) %>%
  rename_with(~ str_replace(., "temp_oa", "oc"), starts_with("temp_oa")) %>%
  rename_with(~ str_replace(., "temp_pa", "pc"), starts_with("temp_pa")) %>%
  rename_with(~ str_replace(., "temp_ob", "os"), starts_with("temp_ob")) %>%
  rename_with(~ str_replace(., "temp_pb", "ps"), starts_with("temp_pb"))

# Assuming your dataframe is named df
for(i in 1:nrow(df)) {
  if(df$oa_condition[i] == 0) {
    df$cho[i] <- -df$cho[i]
  } else if(df$oa_condition[i] == 2) {
  }
}


```

```{r}
# gamble characteristics

df$evc = df$oc1*df$pa1+df$oc2*df$pa2 + df$oc3*df$pa3+df$oc4*df$pa4
df$evs = df$os1*df$pb1+df$os2*df$pb2 + df$os3*df$pb3+df$os4*df$pb4
df$evd = df$evc - df$evs

df$sdc = sqrt((df$oc1-df$evc)^2*df$pa1 + (df$oc2-df$evc)^2*df$pa2 + (df$oc3-df$evc)^2*df$pa3 + (df$oc4-df$evc)^2*df$pa4)
df$sds = sqrt((df$os1-df$evs)^2*df$pb1 + (df$os2-df$evs)^2*df$pb2 + (df$os3-df$evs)^2*df$pb3 + (df$os4-df$evs)^2*df$pb4)
df$sdd = df$sdc - df$sds

```


```{r}
dataList  = list(cho = df$cho, rt = df$rt, participant = df$tid,N=nrow(df),  L = length(tids),starting_point=0.5, evd = df$evd, sdd = df$sdd)

```




```{r}
parameters = c("transf_mu_alpha","transf_mu_threshold","transf_mu_ndt", "transf_mu_theta",'transf_mu_beta', 'sd_threshold',"sd_alpha","sd_ndt", 'sd_theta', 'sd_beta', "alpha_sbj","threshold_sbj","ndt_sbj",'theta_sbj', 'beta_sbj', "log_lik")

initFunc <-function (i) {
  initList=list()
  for (ll in 1:i){
    initList[[ll]] = list(
                          mu_alpha = runif(1,-5,5), 
                          sd_alpha = runif(1,0,1),
                          mu_threshold = runif(1,-0.5,5), 
                          sd_threshold = runif(1,0,1),
                          mu_ndt = runif(1, -1.5, 0),
                          sd_ndt = runif(1, 0, 1),
                          mu_theta = runif(1,-20, 1), 
                          sd_theta = runif(1,0,1),
                          mu_beta = runif(1,-1, 1), 
                          sd_beta = runif(1, 0, 1),
                          z_alpha = runif(length(tids),-0.1,0.1),
                          z_theta = runif(length(tids),-0.1,0.1),
                          z_threshold = runif(length(tids),-0.1,0.1),
                          z_ndt = runif(length(tids),-0.1,0.1),
                          z_beta = runif(length(tids),-0.1,0.1)
                          
                         
    )
  }
  
  return(initList)
}
```


```{r}
m <- stan_model("MV_discount.stan")
dsamples <- sampling(m,  
                data=dataList, 
                pars=parameters,
                iter=1000, 
                chains=4,#If not specified, gives random inits
                init = initFunc(4),
                warmup = 500,  # Stands for burn-in; Default = iter/2
                seed = 12  # Setting seed; Default is random seed
                #refresh = 0
                )
```


```{r}
#parameters = c("transf_mu_alpha","transf_mu_threshold","transf_mu_ndt", "transf_mu_theta",'sd_threshold',"sd_alpha","sd_ndt", 'sd_theta', "alpha_sbj","threshold_sbj","ndt_sbj",'theta_sbj',"log_lik")

rstan::traceplot(dsamples, pars=c("transf_mu_alpha","transf_mu_threshold","transf_mu_ndt", "transf_mu_theta",'transf_mu_beta', 'sd_threshold',"sd_alpha","sd_ndt", 'sd_theta', 'sd_beta', "lp__"), inc_warmup = TRUE, nrow = 3)

pairs(dsamples, pars = c( "transf_mu_alpha","transf_mu_threshold","transf_mu_ndt", "transf_mu_theta",'transf_mu_beta', 'sd_threshold',"sd_alpha","sd_ndt", 'sd_theta', 'sd_beta', "lp__"))
print(dsamples, pars = c("transf_mu_alpha","transf_mu_threshold","transf_mu_ndt", "transf_mu_theta",'transf_mu_beta', 'sd_threshold',"sd_alpha","sd_ndt", 'sd_theta', 'sd_beta', "lp__"))

```

```{r}
library(bayesplot)
ratios_cp <- neff_ratio(dsamples, pars = c("transf_mu_alpha","transf_mu_threshold","transf_mu_ndt", "transf_mu_theta",'transf_mu_beta', 'sd_threshold',"sd_alpha","sd_ndt", 'sd_theta', 'sd_beta',"lp__"))
df_ratios_cp <- as.data.frame(ratios_cp)
print(df_ratios_cp)
mcmc_neff(ratios_cp, size = 2)
```


```{r}
library(ggplot2)
library(tidyverse) # for the gather function

samples_matrix <- as.matrix(dsamples)
means <- colMeans(samples_matrix)
hpd_interval <- t(apply(samples_matrix, 2, function(x) quantile(x, probs=c(0.025, 0.975))))



parameters <- c("transf_mu_alpha","transf_mu_threshold","transf_mu_ndt", "transf_mu_theta",'transf_mu_beta')

# Reshape data to a long format
df_long <- as.data.frame(samples_matrix) %>%
  gather(key = "parameter", value = "value", parameters)

# Convert hpd_interval to a data frame and name the columns
hpd_interval_sub <- hpd_interval[parameters, ]
hpd_df <- as.data.frame(hpd_interval_sub)
colnames(hpd_df) <- c("lower", "upper")
rownames(hpd_df) <- parameters
hpd_df$parameter <- rownames(hpd_df)



# Aesthetic enhancements
theme_set(theme_minimal(base_size = 14)) # Set the default theme

custom_palette <- c("density_fill" = "lightgray", 
                    "mean_line" = "blue", 
                    "hpd_line" = "darkgreen")

# Add text labels for mean, lower, and upper HPD values
df_long <- df_long %>%
  group_by(parameter) %>%
  mutate(mean = means[parameter])

hpd_df <- hpd_df %>%
  mutate(mid = (lower + upper) / 2)

p <- ggplot(df_long, aes(x = value)) + 
  geom_density(aes(fill = "density_fill")) + 
  scale_fill_manual(values = custom_palette, guide = FALSE) +
  geom_vline(aes(xintercept = mean, color = "mean_line"), linetype = "dashed", size = 1, alpha = 0.7) +
  geom_text(data = df_long, aes(x = mean, y = 0, label = round(mean, 2)), vjust = -0.5, hjust = 0.5, size = 4, color = custom_palette["mean_line"]) +
  geom_vline(data = hpd_df, aes(xintercept = lower, color = "hpd_line"), linetype = "solid", size = 1, alpha = 0.5) +
  geom_text(data = hpd_df, aes(x = lower, y = 0, label = round(lower, 2)), vjust = -0.5, hjust = -0.5, size = 4, color = custom_palette["hpd_line"]) +
  geom_vline(data = hpd_df, aes(xintercept = upper, color = "hpd_line"), linetype = "solid", size = 1, alpha = 0.5) +
  geom_text(data = hpd_df, aes(x = upper, y = 0, label = round(upper, 2)), vjust = -0.5, hjust = 1.5, size = 4, color = custom_palette["hpd_line"]) +
  facet_wrap(~ parameter, scales = "free", ncol = 2) +
  scale_color_manual(values = custom_palette, guide = 'none') +
  labs(title = "Posterior distributions")

print(p)
```

