---
title: "prior checks"
output: html_document
date: "2023-10-01"
---



```{r}
mu_ndt = rnorm(10000, 1, 1)
sd_ndt = rnorm(10000, 0, 1)
z_ndt = rnorm(10000, 0, 1)


ndt_1 <- numeric(10000)

for (i in 1:10000) {
  ndt_1[i] <- log(1 + exp(mu_ndt[i] + z_ndt[i]*sd_ndt[i]))
}

# Calculate mean and median of ndt_1
mean_ndt_1 <- mean(ndt_1)
median_ndt_1 <- median(ndt_1)

# Plot the histogram
hist(ndt_1, main="prior distribution of ndt", xlab="Value", ylab="Frequency", col="lightblue", border="black")

# Add the mean and median as vertical lines
abline(v = mean_ndt_1, col="red", lwd=2)
abline(v = median_ndt_1, col="blue", lwd=2, lty=2)  # Using dashed line for median

# Display the values of mean and median
text(mean_ndt_1, par("usr")[4]*0.9, labels=sprintf("Mean = %.2f", mean_ndt_1), col="red", adj=c(1.2, 0))
text(median_ndt_1, par("usr")[4]*0.8, labels=sprintf("Median = %.2f", median_ndt_1), col="blue", adj=c(-0.2, 0))


# Add a legend
legend("topright", legend=c("Mean", "Median"), col=c("red", "blue"), lty=c(1,2), lwd=2)

```

```{r}
mu_ndt = runif(10000, -1.5, -0.2) # Initially guessing ranges
z_ndt = runif(10000, -0.1, 0.1)
sd_ndt = runif(10000, 0, 1)

ndt_1 = numeric(10000) # Initialize ndt_1

for (i in 1:10000) {
  ndt_1[i] <- log(1 + exp(mu_ndt[i] + z_ndt[i]*sd_ndt[i]))
}

# Plot histogram
hist(ndt_1, main="initial value distribution of ndt", xlab="Value", ylab="Frequency", col="lightblue", border="black")

# Find and print the maximum value of ndt_1
max_val <- max(ndt_1)
text(x=max_val, y=par("usr")[4]*0.85, labels=sprintf("Max: %.2f", max_val), col="red", adj=c(1.2, 0))

# Find and print the mean value of ndt_1
mean_val <- mean(ndt_1)
text(x=mean_val, y=par("usr")[4]*0.75, labels=sprintf("Mean: %.2f", mean_val), col="blue")

# Find and print the median value of ndt_1
median_val <- median(ndt_1)
text(x=median_val, y=par("usr")[4]*0.65, labels=sprintf("Median: %.2f", median_val), col="green")

```


```{r}
mu_threshold = rnorm(10000, 1, 3)
sd_threshold = rnorm(10000, 0, 3)
z_threshold = rnorm(10000, 0, 1)


threshold_1 <- numeric(10000)

for (i in 1:10000) {
  threshold_1[i] <- log(1 + exp(mu_threshold[i] + z_threshold[i]*sd_threshold[i]))
}

# Calculate mean and median of threshold_1
mean_threshold_1 <- mean(threshold_1)
median_threshold_1 <- median(threshold_1)

# Plot the histogram
hist(threshold_1, main="prior distribution of threshold", xlab="Value", ylab="Frequency", col="lightblue", border="black")

# Add the mean and median as vertical lines
abline(v = mean_threshold_1, col="red", lwd=2)
abline(v = median_threshold_1, col="blue", lwd=2, lty=2)  # Using dashed line for median

# Display the values of mean and median
text(mean_threshold_1, par("usr")[4]*0.9, labels=sprintf("Mean = %.2f", mean_threshold_1), col="red", adj=c(-0.3, 0))
text(median_threshold_1, par("usr")[4]*0.8, labels=sprintf("Median = %.2f", median_threshold_1), col="blue", adj=c(0.2, 0))


# Add a legend
legend("topright", legend=c("Mean", "Median"), col=c("red", "blue"), lty=c(1,2), lwd=2)

```


```{r}
mu_alpha = rnorm(1000, 1, 5)
sd_alpha = rnorm(1000, 0, 5)
z_alpha = rnorm(1000, 0, 1)

mu_theta = rnorm(1000, 1, 5)
sd_theta = rnorm(1000, 0, 5)
z_theta = rnorm(1000, 0, 1)


evd = rnorm(1000, 0, 20)
sdd = runif(1000, 10, 40)
cho = sample(c(-1, 1), 1000, replace = TRUE)


alpha_sbj <- numeric(1000)
theta_sbj <- numeric(1000)
drift_ll <- numeric(1000)

for (i in 1:1000) {
  
  alpha_sbj[i] = mu_alpha[i] + z_alpha[i]*sd_alpha[i]
  theta_sbj[i] = log(1 + exp(mu_theta[i] + z_theta[i]*sd_theta[i]))
  drift_ll[i] <- theta_sbj[i] *  (evd[i] + alpha_sbj[i] * sdd[i])*cho[i]
}

# Calculate mean and median of drift_ll
mean_drift_ll <- mean(drift_ll)
median_drift_ll <- median(drift_ll)
boxplot(drift_ll)
# Plot the histogram
hist(drift_ll, main="prior distribution of drift_ll", xlab="Value", ylab="Frequency", col="lightblue", border="black" )


# Add the mean and median as vertical lines
abline(v = mean_drift_ll, col="red", lwd=2)
abline(v = median_drift_ll, col="blue", lwd=2, lty=2)  # Using dashed line for median

# Display the values of mean and median
text(mean_drift_ll, par("usr")[4]*0.9, labels=sprintf("Mean = %.2f", mean_drift_ll), col="red", adj=c(-0.3, 0))
text(median_drift_ll, par("usr")[4]*0.8, labels=sprintf("Median = %.2f", median_drift_ll), col="blue", adj=c(0.2, 0))


# Add a legend
legend("topright", legend=c("Mean", "Median"), col=c("red", "blue"), lty=c(1,2), lwd=2)



hist(alpha_sbj, main="prior distribution of alpha_sbj", xlab="Value", ylab="Frequency", col="lightblue", border="black")
hist(theta_sbj, main="prior distribution of theta_sbj", xlab="Value", ylab="Frequency", col="lightblue", border="black")
```




