---
output:
  pdf_document: default
  html_document: default
---

```{r}
ddm4 <- "
data {
	int<lower=1> N;									// number of data item
	int<lower=-1,upper=1> cho[N];				// accuracy (-1, 1)
	real<lower=0> rt[N];							// rt
  real oa[N,2];
  real ob[N,2];
  real pa[N,2];
  real pb[N,2];
  real<lower=0, upper=1> starting_point;			// starting point diffusion model not to estimate
  int<lower=-1,upper=1> con[N];
	
}
parameters {
	real alpha_v;
	real theta_v;
	real threshold_v;
	real ndt_v;
	real delta_theta;


}
transformed parameters {
	real drift_ll[N];								// trial-by-trial drift rate for likelihood (incorporates accuracy)
	real drift_t[N];								// trial-by-trial drift rate for predictions
	real ua[N];	
	real ub[N];	
	real<lower=0> threshold_t[N];					// trial-by-trial threshold
	real<lower=0> ndt_t[N];							// trial-by-trial ndt
	
	real<lower=0> alpha_sbj;
	real<lower=0> theta_sbj;
	real<lower=0> threshold_sbj;
	real<lower=0> ndt_sbj;

	alpha_sbj = log(1 + exp(alpha_v));
	theta_sbj = log(1 + exp(theta_v));
	threshold_sbj = log(1 + exp(threshold_v));
	ndt_sbj = log(1 + exp(ndt_v));


	for (n in 1:N) {
		ua[n] = pa[n,1] * pow(oa[n,1], alpha_sbj) + pa[n,2] * pow(oa[n,2], alpha_sbj);
		ub[n] = pb[n,1] * pow(ob[n,1], alpha_sbj) + pb[n,2] * pow(ob[n,2], alpha_sbj);
		drift_t[n] = (theta_sbj + delta_theta * con[n]) * (ua[n] - ub[n]);
		drift_ll[n] = drift_t[n]*cho[n];
		threshold_t[n] = threshold_sbj;
		ndt_t[n] = ndt_sbj;

	}
}
model {
	alpha_v ~ normal(0.5413, 2);
	theta_v ~ normal(1, 5);
	threshold_v ~ normal(1,3);
	ndt_v ~ normal(0,1);
	delta_theta  ~ normal(0,3);


	rt ~ wiener(threshold_t, ndt_t, starting_point, drift_ll);
}
generated quantities {
	vector[N] log_lik;

	{for (n in 1:N) {
		log_lik[n] = wiener_lpdf(rt[n] | threshold_t[n], ndt_t[n], starting_point, drift_ll[n]);
	}
}
}

"

```


```{r}
library(rstan)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
library(RWiener)
th_p =  4.62 
ndt_p =   1.29
sp_p =  .5 
theta_p = 7.91
alpha_p = 0.07
delta_theta_p = -1.46


dat <- read.csv('final_data.csv')

dat <- dat %>%
  filter(test_part == 'cc' | test_part == 'ss',
         skew %in% c("rl", "lr", 'ns'),
         subject == '4xf5xlk2') %>%
  select(P_A1, O_A1, P_A2, O_A2, P_B1, O_B1, P_B2, O_B2, eva, evb, evd, sda, sdb, sdd, test_part)

dat$con = ifelse(dat$test_part == 'cc', 1, -1)


columns_to_modify <- c('P_A1',  'P_A2', 'P_B1', 'P_B2')


for(column in columns_to_modify) {
  dat[[column]] <- dat[[column]] / 100
}

dat$evd_cat <- cut(dat$evd, 
                  breaks = c(-Inf, -15, -5, 5, 15, Inf), 
                  labels = c("-20", "-10", "0", "10", "20"), 
                  right = FALSE)

dat$sdd_cat <- cut(dat$sdd, 
                  breaks = c(-Inf, 6, 11, 16), 
                  labels = c('5', "10", "15"), 
                  right = FALSE)

stim <- dat[order(dat$evd_cat, dat$sdd_cat, dat$con), ]


stim2 = stim
stim3 = stim

  
  
for(n in 1:nrow(stim2)){
    
    stim2$simchosum[n] = 0
}

stim4 = stim
for(n in 1:nrow(stim4)){
    
    stim4$simchosum[n] = 0
}

    


oa = as.matrix(stim[, c("O_A1", "O_A2")])
ob = as.matrix(stim[, c("O_B1", "O_B2")])
pa = as.matrix(stim[, c("P_A1", "P_A2")])
pb = as.matrix(stim[, c("P_B1", "P_B2")])



```












```{r warning=FALSE}
# Set the number of iterations
n_iter <- 20


`%+=%` = function(e1,e2) eval.parent(substitute(e1 <- e1 + e2))

# Create empty vectors to store the outcome parameters for each iteration
th_p_recover <- numeric(n_iter)
theta_p_recover <- numeric(n_iter)
ndt_p_recover <- numeric(n_iter)
alpha_p_recover <- numeric(n_iter)
delta_theta_p_recover <- numeric(n_iter)

th_p_bias <- numeric(n_iter)
theta_p_bias <- numeric(n_iter)
ndt_p_bias <- numeric(n_iter)
alpha_p_bias <- numeric(n_iter)
delta_theta_p_bias <- numeric(n_iter)

th_p_dev <- numeric(n_iter)
theta_p_dev <- numeric(n_iter)
ndt_p_dev <- numeric(n_iter)
alpha_p_dev <- numeric(n_iter)
delta_theta_p_dev <- numeric(n_iter)


initFunc <-function (i) {
  initList=list()
  for (ll in 1:i){
    initList[[ll]] = list(
                          alpha_sbj = runif(1,-5,5),
                          theta_v = runif(1,-4,6),
                          threshold_v = runif(1,-0.5,2.5),
                          ndt_v = runif(1,-1.5, 0),
                          delta_theta = runif(1,-5,5)
    )
  }
  return(initList)
}



# Run the model for n_iter iterations
for (i in 1:n_iter) {
  
  
  for(n in 1:nrow(stim)){
    cres <- rwiener(1,th_p, ndt_p, sp_p, (theta_p + delta_theta_p * stim$con[n])  * ((pb[n,1] * (ob[n,1]^alpha_p) + pb[n,2] * (ob[n,2]^alpha_p)) - (pa[n,1] * (oa[n,1]^alpha_p) + pa[n,2] * (oa[n,2]^alpha_p))
       
		
		))
    stim$simrt[n] <- as.numeric(cres[1]) 
    stim$simcho[n] <- ifelse(cres[2]=="upper",1,-1)
    stim$cho2[n] <- ifelse(stim$simcho[n] == 1, 0, ifelse(stim$simcho[n] == -1, 1, NA))
    
    }
    
    

  for(n in 1:nrow(stim2)){
    
    stim2$simchosum[n]  %+=% ifelse(stim$simcho[n]==1,1,0)
    }
  
  
  
  
  parameters = c("alpha_sbj","threshold_sbj","ndt_sbj",'theta_sbj', 'delta_theta')
  
  dataList  = list(cho = stim$simcho, rt = stim$simrt, N=90, starting_point=0.5,
                 oa = as.matrix(stim[, c("O_A1", "O_A2")]),
                 ob = as.matrix(stim[, c("O_B1", "O_B2")]),
                 pa = as.matrix(stim[, c("P_A1", "P_A2")]),
                 pb = as.matrix(stim[, c("P_B1", "P_B2")]),
                 con = stim$con
                 )
  


  
  
  # Run the diffusion model for the current iteration
  dsamples <- stan(model_code = ddm4,  
                data=dataList, 
                pars=parameters,
                iter=1000, 
                chains=4,#If not specified, gives random inits
                init=initFunc(4),
                warmup = 500,  # Stands for burn-in; Default = iter/2
                refresh = 0
                )
  
  samples <- extract(dsamples, pars = c("alpha_sbj","threshold_sbj","ndt_sbj",'theta_sbj', 'delta_theta'))
  
  
  # Store the outcome parameters for the current iteration
  th_p_recover[i] <- mean(samples$threshold_sbj)
  theta_p_recover[i] <- mean(samples$theta_sbj)
  ndt_p_recover[i] <- mean(samples$ndt_sbj)
  alpha_p_recover[i] <- mean(samples$alpha_sbj)
  delta_theta_p_recover[i] <- mean(samples$delta_theta)

  
  
  
  th_p_bias[i] <- (mean(samples$threshold_sbj)-th_p)/th_p
  theta_p_bias[i] <- (mean(samples$theta_sbj)-theta_p)/theta_p
  ndt_p_bias[i] <- (mean(samples$ndt_sbj)-ndt_p)/ndt_p
  alpha_p_bias[i] <- (mean(samples$alpha_sbj)-alpha_p)/alpha_p
  delta_theta_p_bias[i] <- (mean(samples$delta_theta)-delta_theta_p)/delta_theta_p

  
  
  th_p_dev[i] <- abs(mean(samples$threshold_sbj)-th_p)/th_p
  theta_p_dev[i] <- abs(mean(samples$theta_sbj)-theta_p)/theta_p
  ndt_p_dev[i] <- abs(mean(samples$ndt_sbj)-ndt_p)/ndt_p
  alpha_p_dev[i] <- abs(mean(samples$alpha_sbj)-alpha_p)/alpha_p
  delta_theta_p_dev[i] <- abs(mean(samples$delta_theta)-delta_theta_p)/delta_theta_p

  
  
  
}
```

```{r}
stim
```


```{r warning=FALSE}

#create a summary df of all parameters
df_summary <- data.frame(original_th_p = th_p, 
                 recovered_th_p = th_p_recover,
                 bias_th_p = th_p_bias,
                 deviation_th_p = th_p_dev,
                 original_theta_p = theta_p, 
                 recovered_theta_p = theta_p_recover,
                 bias_theta_p = theta_p_bias,
                 deviation_theta_p = theta_p_dev,
                 original_ndt_p = ndt_p, 
                 recovered_ndt_p = ndt_p_recover,
                 bias_ndt_p = ndt_p_bias,
                 deviation_ndt_p = ndt_p_dev,
                 original_alpha_p = alpha_p, 
                 recovered_alpha_p = alpha_p_recover,
                 bias_alpha_p = alpha_p_bias,
                 deviation_alpha_p = alpha_p_dev,
                 original_delta_theta_p = delta_theta_p, 
                 recovered_delta_theta_p = delta_theta_p_recover,
                 bias_delta_theta_p = delta_theta_p_bias,
                 deviation_delta_theta_p = delta_theta_p_dev)



```


```{r}
#create a table to show all means and true values
df_mean <- data.frame(parameter = c('th_p', "theta_p", "ndt_p", "alpha_p", 'delta_theta_p'),
                      true_value = c(th_p, theta_p,ndt_p, alpha_p, delta_theta_p),
                      mean_recovered = c(mean(df_summary$recovered_th_p), mean(df_summary$recovered_theta_p),mean(df_summary$recovered_ndt_p),mean(df_summary$recovered_alpha_p), mean(df_summary$recovered_delta_theta_p)),
                      mean_bias = c(mean(df_summary$bias_th_p), mean(df_summary$bias_theta_p),mean(df_summary$bias_ndt_p),mean(df_summary$bias_alpha_p), mean(df_summary$bias_delta_theta_p)),
                      mean_deviation = c(mean(df_summary$deviation_th_p), mean(df_summary$deviation_theta_p),mean(df_summary$deviation_ndt_p),mean(df_summary$deviation_alpha_p), mean(df_summary$deviation_delta_theta_p))
                 )
df_mean
```
```{r}
df_median <- data.frame(parameter = c('th_p', "theta_p", "ndt_p", "alpha_p", 'delta_theta_p'),
                      true_value = c(th_p, theta_p,ndt_p, alpha_p, delta_theta_p),
                      median_recovered = c(median(df_summary$recovered_th_p), median(df_summary$recovered_theta_p),median(df_summary$recovered_ndt_p),median(df_summary$recovered_alpha_p), median(df_summary$recovered_delta_theta_p))
                      )

df_median

```
```{r}
#check whether the risky choice proportion can be successfully recovered by the mean-variance model
#firstly, use recovered parameter values to simulation choice data 

oa = as.matrix(stim[, c("O_A1", "O_A2")])
ob = as.matrix(stim[, c("O_B1", "O_B2")])
pa = as.matrix(stim[, c("P_A1", "P_A2")])
pb = as.matrix(stim[, c("P_B1", "P_B2")])


for (i in 1:n_iter) {

  for(n in 1:nrow(stim3)){
      cres <- rwiener(1,mean(df_summary$recovered_th_p), mean(df_summary$recovered_ndt_p), sp_p, (mean(df_summary$recovered_theta_p) + mean(df_summary$recovered_delta_theta_p) * con[n]) * ((pb[n,1] * (ob[n,1]^mean(df_summary$recovered_alpha_p)) + pb[n,2] * (ob[n,2]^mean(df_summary$recovered_alpha_p))) - (pa[n,1] * (oa[n,1]^mean(df_summary$recovered_alpha_p)) + pa[n,2] * (oa[n,2]^mean(df_summary$recovered_alpha_p)))))
      stim3$simrt[n] <- as.numeric(cres[1]) 
      stim3$simcho[n] <- ifelse(cres[2]=="upper",1,-1)
      stim3$cho2[n] <- ifelse(stim3$simcho[n] == 1, 0, ifelse(stim3$simcho[n] == -1, 1, NA))
    
  }
  for(n in 1:nrow(stim4)){
    
    stim4$simchosum[n]  %+=% ifelse(stim3$simcho[n]==1,1,0)
    
    }
}

```



```{r}
#create summary dataframe
#create summary dataframe
label <- c(rep("basic", 90), rep("recovered", 90))
df <- data.frame(trial = rep(1:90, 2),
                 value = c(stim2$simchosum/n_iter, stim4$simchosum/n_iter),
                 type = rep(label))
#display the first n trials
subset_data <- df[df$trial <= 90, ]

```

```{r}
library(ggplot2)
ggplot(subset_data, aes(x = factor(trial), y = value, fill = type, colour = type)) + 
  geom_bar(stat = "identity", position = "dodge")+
  ylim(0,1)
```




```{r}
library(rstan)
library(RWiener)
th_p =  4.51 
ndt_p =   1.1 
sp_p =  .5 
theta_p = 0.1


stim5 = read.csv('Switching-Gambles.csv')
stim6 = read.csv('Switching-Gambles.csv')
for(n in 1:nrow(stim6)){
    
    stim6$simchosum[n] = 0
}
stim7 = read.csv('Switching-Gambles.csv')
stim8 = read.csv('Switching-Gambles.csv')

for(n in 1:nrow(stim8)){
    
    stim8$simchosum[n] = 0
    
}
    

oa = as.matrix(stim5[, c("payoffa1", "payoffa2")])
ob = as.matrix(stim5[, c("payoffb1", "payoffb2")])
pa = as.matrix(stim5[, c("proba1", "proba2")])
pb = as.matrix(stim5[, c("probb1", "probb2")])




```












```{r warning=FALSE}
# Set the number of iterations
n_iter <- 100


`%+=%` = function(e1,e2) eval.parent(substitute(e1 <- e1 + e2))

# Create empty vectors to store the outcome parameters for each iteration
th_p_recover <- numeric(n_iter)
theta_p_recover <- numeric(n_iter)
ndt_p_recover <- numeric(n_iter)
alpha_p_recover <- numeric(n_iter)

th_p_bias <- numeric(n_iter)
theta_p_bias <- numeric(n_iter)
ndt_p_bias <- numeric(n_iter)
alpha_p_bias <- numeric(n_iter)

th_p_dev <- numeric(n_iter)
theta_p_dev <- numeric(n_iter)
ndt_p_dev <- numeric(n_iter)
alpha_p_dev <- numeric(n_iter)


alpha_p_set = numeric(n_iter)


# Run the model for n_iter iterations
for (i in 1:n_iter) {
  
  # Set the range (minimum and maximum values)
  min_value <- 0.2
  max_value <- 1.5
  
  
   # Generate a single random non-zero value within the range
  alpha_p <- 0
  while (alpha_p == 0) {
    alpha_p <- sample(seq(min_value, max_value, length.out = 100), 1)
  }
  alpha_p_set[i] = alpha_p
  
  
  
  for(n in 1:nrow(stim5)){
    cres <- rwiener(1,th_p, ndt_p, sp_p, theta_p * ((pb[n,1] * (ob[n,1]^alpha_p) + pb[n,2] * (ob[n,2]^alpha_p)) - (pa[n,1] * (oa[n,1]^alpha_p) + pa[n,2] * (oa[n,2]^alpha_p))))
    stim5$simrt[n] <- as.numeric(cres[1]) 
    stim5$simcho[n] <- ifelse(cres[2]=="upper",1,-1)
    
    }
    
    

  for(n in 1:nrow(stim6)){
    
    stim6$simchosum[n]  %+=% ifelse(stim5$simcho[n]==1,1,0)
    }
  
  
  
  
  parameters = c("alpha_sbj","threshold_sbj","ndt_sbj",'theta_sbj')
  dataList  = list(cho = stim5$simcho,rt = stim5$simrt, N=60, starting_point=0.5, 
                 oa = as.matrix(stim5[, c("payoffa1", "payoffa2")]),
                 ob = as.matrix(stim5[, c("payoffb1", "payoffb2")]),
                 pa = as.matrix(stim5[, c("proba1", "proba2")]),
                 pb = as.matrix(stim5[, c("probb1", "probb2")])
                 )
  


  
  
  # Run the diffusion model for the current iteration
  dsamples <- stan(model_code = ddm4,  
                data=dataList, 
                pars=parameters,
                iter=1000, 
                chains=4,#If not specified, gives random inits
                init=initFunc(4),
                warmup = 500,  # Stands for burn-in; Default = iter/2
                refresh = 0
                )
  
  samples <- extract(dsamples, pars = c('alpha_sbj', 'theta_sbj', 'threshold_sbj', 'ndt_sbj'))
  
  
  # Store the outcome parameters for the current iteration
  th_p_recover[i] <- mean(samples$threshold_sbj)
  theta_p_recover[i] <- mean(samples$theta_sbj)
  ndt_p_recover[i] <- mean(samples$ndt_sbj)
  alpha_p_recover[i] <- mean(samples$alpha_sbj)
  
  
  
  th_p_bias[i] <- (mean(samples$threshold_sbj)-th_p)/th_p
  theta_p_bias[i] <- (mean(samples$theta_sbj)-theta_p)/theta_p
  ndt_p_bias[i] <- (mean(samples$ndt_sbj)-ndt_p)/ndt_p
  alpha_p_bias[i] <- (mean(samples$alpha_sbj)-alpha_p)/alpha_p
  
  
  th_p_dev[i] <- abs(mean(samples$threshold_sbj)-th_p)/th_p
  theta_p_dev[i] <- abs(mean(samples$theta_sbj)-theta_p)/theta_p
  ndt_p_dev[i] <- abs(mean(samples$ndt_sbj)-ndt_p)/ndt_p
  alpha_p_dev[i] <- abs(mean(samples$alpha_sbj)-alpha_p)/alpha_p

  
  
  
}
```


```{r}
# Load the required library
library(ggplot2)



# Create a data frame with the vectors
data <- data.frame(alpha_p_set, alpha_p_recover)

# Calculate the correlation coefficient
correlation <- cor(alpha_p_set, alpha_p_recover, method = "spearman")

# Create the scatter plot with correlation line using ggplot2
ggplot(data, aes(x = alpha_p_set, y = alpha_p_recover)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  labs(x = "alpha_p_set", y = "alpha_p_recover") +
  annotate("text", x = 1, y = 1, label = paste0("Correlation: ", round(correlation, 2)), hjust = 2, vjust = 0.8, color = "red")


```




