```{r}
############### 0 - safe choice A, 1 - risky choice B #####################
library(rstan); rstan_options(javascript=FALSE)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = T)

# Get list of files in 'data_2' folder with the pattern "riskytimed"
files <- dir(path = "data_2", pattern="riskytimed")

# Read all csv files in the list
data_list <- lapply(paste0("data_2/", files), read.table, header = TRUE, skip = 0, fill = TRUE, sep= ";")

# Concatenate rows of all items in the list into a data frame
dat <- do.call("rbind", data_list)
```

```{r}
# gamble characteristics
dat$eva = dat$oa1*dat$pa1+dat$oa2*dat$pa2 + dat$oa3*dat$pa3+dat$oa4*dat$pa4
dat$evb = dat$ob1*dat$pb1+dat$ob2*dat$pb2 + dat$ob3*dat$pb3+dat$ob4*dat$pb4
dat$evd = dat$evb - dat$eva
dat$sda = sqrt((dat$oa1-dat$eva)^2*dat$pa1 + (dat$oa2-dat$eva)^2*dat$pa2 + (dat$oa3-dat$eva)^2*dat$pa3 + (dat$oa4-dat$eva)^2*dat$pa4)
dat$sdb = sqrt((dat$ob1-dat$evb)^2*dat$pb1 + (dat$ob2-dat$evb)^2*dat$pb2 + (dat$ob3-dat$evb)^2*dat$pb3 + (dat$ob4-dat$evb)^2*dat$pb4)
dat$sdd = dat$sdb - dat$sda
dat$evdummy = ifelse(dat$evd>0,1,0)


```

```{r}
# transform to +/- 1; safe - 1, risky +1
dat$cho <- ifelse(dat$choice==0,-1,ifelse(dat$choice==1,1,NA))
dat$cho2 <- ifelse(dat$choice==0,1,ifelse(dat$choice==1,0,NA))
ids <- unique(dat$id)
for(j in 1:length(ids)){
  dat$tid[dat$id==ids[j]] <- j
}
tids <- unique(dat$tid)
# only control data
control_dat <- dat[dat$cond=="control",]
# remove fast RTs
rcontrol_dat <- control_dat[control_dat$rt>1,]
rcontrol_dat
# only condition no time pressure
dataList  = list(cho = rcontrol_dat$cho, accuracy_flipped = rcontrol_dat$cho2, rt = rcontrol_dat$rt, participant = rcontrol_dat$tid,N=nrow(rcontrol_dat),  L = length(tids), evd = rcontrol_dat$evd, sdd = rcontrol_dat$sdd)

```


```{r}
oa = as.matrix(rcontrol_dat[, c("oa1", "oa2", "oa3", "oa4")])
ob = as.matrix(rcontrol_dat[, c("ob1", "ob2", "ob3", "ob4")])
pa = as.matrix(rcontrol_dat[, c("pa1", "pa2", "pa3", "pa4")])
pb = as.matrix(rcontrol_dat[, c("pb1", "pb2", "pb3", "pb4")])
```

```{r}
dataList  = list(cho = rcontrol_dat$cho, accuracy_flipped = rcontrol_dat$cho2, rt = rcontrol_dat$rt, participant = rcontrol_dat$tid,N=nrow(rcontrol_dat),  L = length(tids), 
                 oa = as.matrix(rcontrol_dat[, c("oa1", "oa2", "oa3", "oa4")]),
                 ob = as.matrix(rcontrol_dat[, c("ob1", "ob2", "ob3", "ob4")]),
                 pa = as.matrix(rcontrol_dat[, c("pa1", "pa2", "pa3", "pa4")]),
                 pb = as.matrix(rcontrol_dat[, c("pb1", "pb2", "pb3", "pb4")])
                 )

parameters = c("transf_mu_alpha","transf_mu_threshold","transf_mu_ndt", "transf_mu_theta",'transf_mu_rel_sp', 'sd_threshold',"sd_alpha","sd_ndt", 'sd_theta', 'sd_rel_sp', "alpha_sbj","threshold_sbj","ndt_sbj",'theta_sbj', 'rel_sp_sbj', "log_lik")

```



```{r}
initFunc <-function (i) {
  initList=list()
  for (ll in 1:i){
    initList[[ll]] = list(
                          mu_alpha = runif(1,-.5,.5), 
                          sd_alpha = runif(1,0,1),
                          mu_threshold = runif(1,-0.5, 0.5), 
                          sd_threshold = runif(1,0,1),
                          mu_ndt = runif(1, -1.5, 0),
                          sd_ndt = runif(1, 0, 1),
                          mu_theta = runif(1,-0.5, -0.5), 
                          sd_theta = runif(1,0,1),
                          mu_rel_sp = runif(1,-0.5, -0.5), 
                          sd_rel_sp = runif(1, 0, 1),
                          z_alpha = runif(length(tids),-0.1,0.1),
                          z_theta = runif(length(tids),-0.1,0.1),
                          z_threshold = runif(length(tids),-0.1,0.1),
                          z_ndt = runif(length(tids),-0.1,0.1),
                          z_rel_sp = runif(length(tids),-0.1,0.1)
    )
  }
  
  return(initList)
}
```


```{r}
m <- stan_model("EU_SP.stan")
dsamples <- sampling(m,  
                data=dataList, 
                pars=parameters,
                iter=2000, 
                chains=4,#If not specified, gives random inits
                init = initFunc(4),
                warmup = 1000,  # Stands for burn-in; Default = iter/2
                seed = 12  # Setting seed; Default is random seed
                #refresh = 0
                )

```

```{r}

rstan::traceplot(dsamples, pars=c("transf_mu_alpha","transf_mu_threshold","transf_mu_ndt", "transf_mu_theta",'transf_mu_rel_sp', 'sd_threshold',"sd_alpha","sd_ndt", 'sd_theta', 'sd_rel_sp', "lp__"), inc_warmup = TRUE, nrow = 3)

pairs(dsamples, pars = c( "transf_mu_alpha","transf_mu_threshold","transf_mu_ndt", "transf_mu_theta",'transf_mu_rel_sp', 'sd_threshold',"sd_alpha","sd_ndt", 'sd_theta', 'sd_rel_sp', "lp__"))
print(dsamples, pars = c("transf_mu_alpha","transf_mu_threshold","transf_mu_ndt", "transf_mu_theta",'transf_mu_rel_sp', 'sd_threshold',"sd_alpha","sd_ndt", 'sd_theta', 'sd_rel_sp', "lp__"))
```


```{r}
ratios_cp <- neff_ratio(dsamples, pars = c("transf_mu_alpha","transf_mu_theta", "transf_mu_threshold","transf_mu_ndt", 'transf_mu_rel_sp', 'sd_threshold',"sd_alpha","sd_ndt", 'sd_theta', 'sd_rel_sp',"lp__"))
df_ratios_cp <- as.data.frame(ratios_cp)
print(df_ratios_cp)
mcmc_neff(ratios_cp, size = 2)
```
